'use client';

import { ArrowRight, BarChart3, Check, ChevronDown, CircleHelp, Copy, FileText, ImagePlus, Images, LayoutDashboard, Lightbulb, Package, PenLine, Plus, Ruler, Search, Sparkles, Target, WandSparkles } from 'lucide-react';
import { useRef, useState } from 'react';

type Tab = 'overview' | 'images' | 'copy' | 'advisor' | 'score';
const demoImage = 'https://images.rawpixel.com/image_social_landscape/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDI0LTA3L3dvcmxkZmFjZXNsYWJfdmludGFnZV9jaGFpcl9zdHVkaW9fbGlnaHRpbmdfd2hpdGVfcGxhaW5fYmFja2dyb183ZmVjYWI2ZC01MjY1LTQxMDMtYjUyNi1kYzZhYmY1NzgzZWIuanBn.jpg';

export default function Home() {
  const inputRef = useRef<HTMLInputElement>(null);
  const [tab, setTab] = useState<Tab>('overview');
  const [fileName, setFileName] = useState('');
  const [product, setProduct] = useState('Poltrona Decorativa Luna');
  const [generated, setGenerated] = useState(false);

  const content = {
    overview: <Overview inputRef={inputRef} fileName={fileName} setFileName={setFileName} product={product} setProduct={setProduct} onContinue={() => setTab('images')} />,
    images: <ImageLab product={product} />,
    copy: <CopyStudio product={product} generated={generated} setGenerated={setGenerated} />,
    advisor: <Advisor />,
    score: <Score />,
  }[tab];

  return (
    <main className="min-h-screen bg-background text-foreground">
      <header className="sticky top-0 z-20 border-b border-border/70 bg-background/92 backdrop-blur-xl">
        <div className="mx-auto flex h-18 max-w-[1500px] items-center justify-between px-5 lg:px-8">
          <button onClick={() => setTab('overview')} className="flex items-center gap-3 text-left"><span className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground shadow-sm"><Sparkles className="size-4.5" /></span><span><span className="block text-[15px] font-extrabold tracking-[-.03em]">VitrineAI</span><span className="block text-[10px] font-bold uppercase tracking-[.18em] text-muted-foreground">Studio de marketplace</span></span></button>
          <div className="flex items-center gap-2"><button className="hidden rounded-xl px-4 py-2 text-sm font-semibold text-muted-foreground transition hover:bg-muted sm:block">Meus projetos</button><button onClick={() => setTab('overview')} className="rounded-xl bg-foreground px-4 py-2 text-sm font-bold text-background transition hover:opacity-90">Novo produto</button></div>
        </div>
      </header>

      <div className="mx-auto grid max-w-[1500px] grid-cols-1 lg:grid-cols-[220px_minmax(0,1fr)]">
        <aside className="border-b border-border/70 px-4 py-3 lg:min-h-[calc(100vh-72px)] lg:border-b-0 lg:border-r lg:py-6">
          <nav className="flex gap-1 overflow-x-auto lg:block lg:space-y-1" aria-label="Navegação principal">
            <NavItem icon={<LayoutDashboard />} label="Visão geral" active={tab === 'overview'} onClick={() => setTab('overview')} />
            <NavItem icon={<Images />} label="Laboratório de imagens" active={tab === 'images'} onClick={() => setTab('images')} />
            <NavItem icon={<PenLine />} label="Títulos e descrição" active={tab === 'copy'} onClick={() => setTab('copy')} />
            <NavItem icon={<Lightbulb />} label="Consultor de vendas" active={tab === 'advisor'} onClick={() => setTab('advisor')} />
            <NavItem icon={<BarChart3 />} label="Análise do anúncio" active={tab === 'score'} onClick={() => setTab('score')} />
          </nav>
          <div className="mt-8 hidden rounded-2xl border border-border bg-card p-4 lg:block"><div className="mb-3 flex items-center justify-between text-xs font-bold"><span>Plano piloto</span><span>3/10</span></div><div className="h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full w-[30%] rounded-full bg-primary" /></div><p className="mt-3 text-xs leading-5 text-muted-foreground">3 pacotes gerados neste mês.</p></div>
        </aside>
        <section className="min-w-0 px-5 py-7 sm:px-7 lg:px-10 lg:py-9">{content}</section>
      </div>
    </main>
  );
}

function PageHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <div className="mb-7"><p className="mb-2 flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.16em] text-primary"><span className="size-1.5 rounded-full bg-primary" />{eyebrow}</p><h1 className="text-3xl font-black tracking-[-.045em] sm:text-4xl">{title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{description}</p></div>;
}

function Overview({ inputRef, fileName, setFileName, product, setProduct, onContinue }: { inputRef: React.RefObject<HTMLInputElement | null>; fileName: string; setFileName: (v: string) => void; product: string; setProduct: (v: string) => void; onContinue: () => void }) {
  return <><PageHeading eyebrow="Novo projeto" title="Transforme uma foto em um anúncio completo." description="Configure o produto uma vez. A VitrineAI prepara imagens, medidas, variações e conteúdo para cada marketplace." />
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(330px,.75fr)]">
      <Card><div className="mb-5 flex items-center justify-between"><Title title="1. Foto do produto" subtitle="Use uma foto nítida, de frente e bem iluminada." /><Badge>OBRIGATÓRIO</Badge></div><button onClick={() => inputRef.current?.click()} className="flex min-h-58 w-full flex-col items-center justify-center rounded-[20px] border border-dashed border-primary/35 bg-primary/[.035] p-8 text-center transition hover:border-primary hover:bg-primary/[.065]"><span className="mb-4 grid size-12 place-items-center rounded-2xl bg-primary text-primary-foreground"><ImagePlus className="size-5" /></span><span className="font-extrabold">{fileName || 'Arraste a foto ou clique para enviar'}</span><span className="mt-2 text-xs text-muted-foreground">JPG, PNG ou WEBP · até 20 MB</span></button><input ref={inputRef} type="file" accept="image/*" className="sr-only" onChange={(event) => setFileName(event.target.files?.[0]?.name || '')} /><div className="mt-7 grid gap-5 sm:grid-cols-2"><Field label="Nome do produto"><input value={product} onChange={(e) => setProduct(e.target.value)} className="input" /></Field><Field label="Categoria"><button className="input flex items-center justify-between text-muted-foreground"><span>Móveis e decoração</span><ChevronDown className="size-4" /></button></Field></div></Card>
      <div className="space-y-5"><Card><div className="mb-5 flex items-start justify-between"><Title title="2. Onde vai vender?" subtitle="Adaptamos regras e conteúdo." /><Package className="size-5 text-primary" /></div><div className="grid grid-cols-2 gap-3"><Marketplace name="Mercado Livre" color="#ffe600" /><Marketplace name="Shopee" color="#ee4d2d" /></div></Card><Card><div className="mb-4 flex items-center justify-between"><Title title="3. Cores" subtitle="Fotos individuais e em coleção." /><button aria-label="Adicionar cor" className="icon-button"><Plus className="size-4" /></button></div><div className="flex flex-wrap gap-2"><Color color="#171717" name="Preto" /><Color color="#1f5fae" name="Azul" /><Color color="#e8dac7" name="Bege" /></div></Card><button onClick={onContinue} className="primary-action"><span><b>Continuar configuração</b><small>Medidas, benefícios e objeções</small></span><ArrowRight className="size-5" /></button></div>
    </div>
    <Card className="mt-7"><div className="mb-5 flex items-end justify-between"><Title title="Seu pacote de conversão" subtitle="10 entregas para informar, gerar confiança e vender." /><span className="hidden text-xs font-bold text-primary sm:block">Baseado nas regras dos marketplaces</span></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Pack icon={<Images />} label="Capa limpa" count="01" /><Pack icon={<Sparkles />} label="Fotos por cor" count="03" /><Pack icon={<Ruler />} label="Medidas visuais" count="01" /><Pack icon={<Package />} label="Produto em uso" count="03" /><Pack icon={<Lightbulb />} label="Quebra de objeções" count="02" /></div></Card>
  </>;
}

function ImageLab({ product }: { product: string }) {
  const [mode, setMode] = useState('pacote');
  return <><PageHeading eyebrow="Laboratório de imagens" title="Uma foto, dez argumentos visuais." description="Monte um conjunto equilibrado entre capa, variações, escala, contexto e respostas às dúvidas do comprador." />
    <div className="grid gap-5 xl:grid-cols-[360px_1fr]"><div className="space-y-5"><Card><Title title={product || 'Seu produto'} subtitle="Configuração do pacote" /><div className="mt-5 space-y-4"><Field label="Tipo de geração"><div className="grid grid-cols-3 gap-2">{['pacote','cor','coleção'].map(v => <button key={v} onClick={() => setMode(v)} className={`rounded-xl border px-2 py-2.5 text-xs font-bold capitalize ${mode === v ? 'border-primary bg-primary/10 text-primary' : 'border-border'}`}>{v}</button>)}</div></Field><Field label="Medidas reais"><div className="grid grid-cols-3 gap-2"><input className="input px-2" placeholder="Largura" /><input className="input px-2" placeholder="Altura" /><input className="input px-2" placeholder="Prof." /></div></Field><Field label="Peso suportado / capacidade"><input className="input" placeholder="Ex.: até 120 kg" /></Field><Field label="Características que não podem mudar"><textarea className="min-h-24 w-full rounded-xl border border-input bg-background p-3 text-sm outline-none focus:border-primary" placeholder="Logo, costura, pés de madeira, textura..." /></Field></div><button className="primary-action mt-5"><span><b>Gerar pacote com 10 imagens</b><small>Estimativa visual pronta para revisar</small></span><WandSparkles className="size-5" /></button></Card></div>
      <Card><div className="mb-5 flex items-center justify-between"><Title title="Roteiro visual recomendado" subtitle="Selecione o que deseja gerar." /><Badge>10 IMAGENS</Badge></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Preview image title="Capa limpa" note="Fundo branco · sem texto" /><Preview image title="Cor azul" note="Produto realista" tint="bg-blue-700/10" /><Preview image title="Cor bege" note="Mesma forma e textura" tint="bg-amber-100" /><Preview title="Medidas" note="L × A × P com setas" icon={<Ruler />} /><Preview title="Em escala" note="Dimensão fácil de entender" icon={<Package />} /><Preview title="Quebra de objeção" note="Conforto e resistência" icon={<CircleHelp />} /><Preview title="Sala de estar" note="Uso real e aspiracional" icon={<Sparkles />} /><Preview title="Detalhe do tecido" note="Textura e acabamento" icon={<Search />} /><Preview title="Todas as cores" note="Preto, azul e bege" icon={<Images />} /><Preview title="Benefícios" note="3 razões para escolher" icon={<Check />} /></div></Card></div>
  </>;
}

function CopyStudio({ product, generated, setGenerated }: { product: string; generated: boolean; setGenerated: (v: boolean) => void }) {
  return <><PageHeading eyebrow="Títulos e descrição" title="Texto que encontra o comprador e reduz dúvidas." description="Cada marketplace recebe uma versão própria: clara, pesquisável e sem promessas que você não consiga comprovar." />
    <div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><Card><Title title="Dados para a escrita" subtitle="Quanto mais preciso, melhor o resultado." /><div className="mt-5 space-y-4"><Field label="Produto"><input className="input" defaultValue={product} /></Field><Field label="Marca e modelo"><input className="input" placeholder="Ex.: Casa Luna · modelo PL02" /></Field><Field label="Material principal"><input className="input" placeholder="Ex.: madeira maciça e tecido linho" /></Field><Field label="Diferenciais comprováveis"><textarea className="min-h-24 w-full rounded-xl border border-input bg-background p-3 text-sm outline-none focus:border-primary" placeholder="Fácil montagem, espuma D28, capa removível..." /></Field><Field label="Palavras que o cliente usa"><input className="input" placeholder="poltrona sala, cadeira leitura..." /></Field></div><button onClick={() => setGenerated(true)} className="primary-action mt-5"><span><b>Gerar títulos e descrição</b><small>Versões para Shopee e Mercado Livre</small></span><Sparkles className="size-5" /></button></Card>
      <div className="space-y-5">{!generated ? <EmptyCopy /> : <><Result platform="Mercado Livre" accent="#ffe600" title="Poltrona Decorativa Luna Tecido Linho Pés De Madeira" reason="Segue produto + marca/modelo + atributos que identificam. Evita cor, promoção e informações repetidas nas variações." /><Result platform="Shopee" accent="#ee4d2d" title="Poltrona Decorativa Luna em Linho com Pés de Madeira para Sala e Quarto" reason="Acrescenta material e contexto de uso de forma natural, mantendo clareza e evitando palavras-chave irrelevantes." /><Card><div className="flex items-center justify-between"><Title title="Descrição sugerida" subtitle="Informação mais importante primeiro." /><button className="icon-button" aria-label="Copiar descrição"><Copy className="size-4" /></button></div><div className="mt-5 space-y-4 text-sm leading-6 text-muted-foreground"><p className="font-bold text-foreground">Conforto e design para transformar seu ambiente.</p><p>A Poltrona Luna combina linhas leves, tecido de toque agradável e estrutura pensada para salas, quartos e cantos de leitura.</p><div className="rounded-2xl bg-muted/50 p-4"><b className="text-foreground">Destaques</b><ul className="mt-2 list-inside list-disc"><li>Revestimento em tecido tipo linho</li><li>Pés de madeira com montagem simples</li><li>Disponível em preto, azul e bege</li></ul></div><p className="text-xs">Antes de publicar, confirme material, capacidade e medidas. A VitrineAI nunca inventa especificações.</p></div></Card></>}</div>
    </div></>;
}

function Advisor() {
  return <><PageHeading eyebrow="Consultor de vendas" title="Boas práticas explicadas, não apenas repetidas." description="Reunimos recomendações oficiais e evidências de experiência de compra para mostrar o que fazer e por que isso ajuda." />
    <div className="grid gap-5 lg:grid-cols-2"><Insight number="01" title="A capa precisa ganhar o clique sem prometer demais" text="No Mercado Livre, use o produto centralizado em fundo branco, sem marca d’água, bordas ou texto promocional. Na Shopee, mantenha formato quadrado, alta resolução e o produto ocupando a maior parte da área." why="Por quê vende: o comprador identifica o item em poucos segundos e a plataforma consegue classificar o anúncio com menos ruído." source="Mercado Livre + Shopee Ads" /><Insight number="02" title="Mostre escala e medidas visualmente" text="Inclua uma imagem com largura, altura e profundidade, mais uma cena em que o comprador reconheça a escala do produto." why="Por quê vende: pesquisas de usabilidade mostram que clientes tentam entender o tamanho pelas imagens; uma referência visual reduz interpretação errada e devolução." source="Baymard Institute" /><Insight number="03" title="Título bom identifica; não grita" text="Comece pelo tipo do produto. Acrescente marca, modelo e especificações decisivas. Evite caixa alta, promoções, frete, repetição e palavras sem relação com a busca." why="Por quê vende: clareza melhora correspondência com a intenção de pesquisa e evita que o comprador clique esperando outro produto." source="Mercado Livre + Shopee Ads" /><Insight number="04" title="Variação deve continuar sendo o mesmo produto" text="Cadastre cores e tamanhos como variações reais, com estoque e imagem coerente para cada opção. Não misture produtos diferentes para exibir um preço artificialmente baixo." why="Por quê vende: consistência entre capa, variação e preço aumenta confiança e reduz reclamações." source="Centrais de ajuda" /><Insight number="05" title="Use de 4 a 8 imagens com funções diferentes" text="Combine capa, ângulos, detalhe, escala, ambiente, embalagem e uso. Não desperdice slots repetindo quase a mesma foto." why="Por quê vende: imagens diferentes ajudam a avaliar acabamento, proporção e adequação; o Mercado Livre relata ganhos de faturamento após melhorias nas fotos." source="Mercado Livre + Baymard" /><Insight number="06" title="Quebre objeções com fatos comprovados" text="Analise perguntas e avaliações da categoria, depois responda visualmente: montagem, limpeza, capacidade, compatibilidade ou conteúdo da embalagem." why="Por quê vende: menos incerteza antes da compra significa menos perguntas, abandono e devoluções. Só use medidas e promessas fornecidas pelo vendedor." source="Síntese da pesquisa" /></div>
    <Card className="mt-5"><Title title="Checklist rápido antes de publicar" subtitle="Uma revisão de 60 segundos." /><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{['Capa limpa e fiel','Título sem exageros','Medidas confirmadas','Variações consistentes','Acessórios identificados','Descrição escaneável','Categoria correta','Sem dados de contato'].map(item => <label key={item} className="flex items-center gap-3 rounded-xl border border-border p-3 text-xs font-bold"><input type="checkbox" className="accent-[var(--primary)]" />{item}</label>)}</div></Card>
  </>;
}

function Score() { return <><PageHeading eyebrow="Análise do anúncio" title="Descubra o que está impedindo a conversão." description="Uma avaliação simples separa problemas de clique, entendimento e confiança para indicar a próxima melhoria." /><div className="grid gap-5 lg:grid-cols-[320px_1fr]"><Card className="text-center"><div className="mx-auto grid size-36 place-items-center rounded-full border-[12px] border-primary/15 text-primary"><span><b className="block text-4xl font-black">78</b><small className="font-bold">de 100</small></span></div><p className="mt-5 font-extrabold">Bom, com espaço para crescer</p><p className="mt-2 text-xs leading-5 text-muted-foreground">As maiores oportunidades estão na imagem de escala e nas especificações.</p></Card><Card><Title title="Prioridades encontradas" subtitle="Corrija na ordem de impacto provável." /><div className="mt-5 space-y-3"><ScoreRow value="92" label="Clareza do título" status="Muito bom" /><ScoreRow value="84" label="Qualidade da capa" status="Bom" /><ScoreRow value="66" label="Escala e medidas" status="Melhorar" /><ScoreRow value="58" label="Quebra de objeções" status="Melhorar" /></div></Card></div></>; }

function NavItem({ icon, label, active, onClick }: { icon: React.ReactNode; label: string; active: boolean; onClick: () => void }) { return <button onClick={onClick} className={`flex shrink-0 items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-semibold transition lg:w-full ${active ? 'bg-primary/10 text-primary' : 'text-muted-foreground hover:bg-muted hover:text-foreground'}`}><span className="[&>svg]:size-4">{icon}</span>{label}</button>; }
function Card({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <div className={`rounded-[24px] border border-border bg-card p-5 shadow-[0_14px_42px_rgba(36,48,41,.04)] sm:p-6 ${className}`}>{children}</div>; }
function Title({ title, subtitle }: { title: string; subtitle: string }) { return <div><p className="text-lg font-extrabold tracking-[-.02em]">{title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{subtitle}</p></div>; }
function Badge({ children }: { children: React.ReactNode }) { return <span className="rounded-full bg-primary/10 px-3 py-1 text-[10px] font-extrabold text-primary">{children}</span>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block space-y-2 text-xs font-bold">{label}{children}</label>; }
function Marketplace({ name, color }: { name: string; color: string }) { return <button className="relative rounded-2xl border border-primary/30 bg-primary/[.04] p-3 text-left"><span className="mb-3 block size-3 rounded-full" style={{ background: color }} /><span className="text-xs font-extrabold">{name}</span><span className="absolute right-2.5 top-2.5 grid size-5 place-items-center rounded-full bg-primary text-primary-foreground"><Check className="size-3" /></span></button>; }
function Color({ color, name }: { color: string; name: string }) { return <span className="flex items-center gap-2 rounded-full border border-border bg-background py-1.5 pl-1.5 pr-3 text-xs font-bold"><span className="size-6 rounded-full border border-black/10" style={{ background: color }} />{name}</span>; }
function Pack({ icon, label, count }: { icon: React.ReactNode; label: string; count: string }) { return <div className="flex items-center gap-3 rounded-2xl border border-border/70 bg-muted/35 p-3"><span className="grid size-9 place-items-center rounded-xl bg-background text-primary shadow-sm [&>svg]:size-4">{icon}</span><span><span className="block text-[10px] font-black tracking-[.12em] text-muted-foreground">{count}</span><span className="block text-xs font-extrabold">{label}</span></span></div>; }
function Preview({ image, title, note, tint = '', icon }: { image?: boolean; title: string; note: string; tint?: string; icon?: React.ReactNode }) { return <label className="group relative overflow-hidden rounded-2xl border border-border bg-background"><input type="checkbox" defaultChecked className="absolute right-3 top-3 z-10 size-4 accent-[var(--primary)]" /><div className={`grid aspect-[4/3] place-items-center overflow-hidden bg-muted ${tint}`}>{image ? <img src={demoImage} alt="Poltrona azul de demonstração" className="h-full w-full object-contain p-3" /> : <span className="text-primary [&>svg]:size-7">{icon}</span>}</div><div className="p-3"><p className="text-xs font-extrabold">{title}</p><p className="mt-1 text-[11px] text-muted-foreground">{note}</p></div></label>; }
function EmptyCopy() { return <Card className="grid min-h-72 place-items-center text-center"><div><span className="mx-auto grid size-12 place-items-center rounded-2xl bg-primary/10 text-primary"><FileText className="size-5" /></span><p className="mt-4 font-extrabold">Pronto para escrever</p><p className="mx-auto mt-2 max-w-xs text-xs leading-5 text-muted-foreground">Preencha os dados reais do produto. A ferramenta criará versões próprias para cada marketplace.</p></div></Card>; }
function Result({ platform, accent, title, reason }: { platform: string; accent: string; title: string; reason: string }) { return <Card><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-xs font-extrabold"><i className="size-3 rounded-full" style={{ background: accent }} />{platform}</span><button className="icon-button"><Copy className="size-4" /></button></div><p className="mt-4 text-lg font-black leading-7 tracking-[-.02em]">{title}</p><div className="mt-4 rounded-xl bg-muted/55 p-3 text-xs leading-5 text-muted-foreground"><b className="text-foreground">Por que funciona: </b>{reason}</div></Card>; }
function Insight({ number, title, text, why, source }: { number: string; title: string; text: string; why: string; source: string }) { return <Card><div className="flex items-start justify-between"><span className="text-xs font-black tracking-[.15em] text-primary">{number}</span><Target className="size-4 text-primary" /></div><h2 className="mt-4 text-lg font-extrabold tracking-[-.025em]">{title}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p><p className="mt-4 rounded-xl bg-primary/[.055] p-3 text-xs leading-5"><b>{why.split(':')[0]}:</b>{why.split(':').slice(1).join(':')}</p><p className="mt-3 text-[10px] font-bold uppercase tracking-[.12em] text-muted-foreground">Fonte: {source}</p></Card>; }
function ScoreRow({ value, label, status }: { value: string; label: string; status: string }) { return <div className="grid grid-cols-[42px_1fr_auto] items-center gap-3 rounded-2xl border border-border p-3"><span className="grid size-10 place-items-center rounded-xl bg-primary/10 text-xs font-black text-primary">{value}</span><span className="text-sm font-bold">{label}</span><span className="text-xs font-semibold text-muted-foreground">{status}</span></div>; }
