'use client';
import { useState, type CSSProperties } from 'react';
import { ArrowRight, LockKeyhole, MessageCircle, PackageOpen, Search, ShoppingBag } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { imageUrl, money, type CatalogData } from '@/lib/catalog-types';

export default function Catalog({ settings, products }: CatalogData) {
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState('Todos');
  const categories = ['Todos', ...new Set(products.map(p => p.category).filter(Boolean))];
  const filtered = products.filter(p => (category === 'Todos' || p.category === category) && `${p.name} ${p.description} ${p.category} ${p.colors}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')));
  const contact = settings.whatsapp ? `https://wa.me/${settings.whatsapp}` : '';
  return <main style={{ '--catalog-accent': settings.accent } as CSSProperties} className="min-h-screen">
    <header className="border-b border-border bg-background/95"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-5 py-5 sm:px-8">
      <a href="/" className="flex items-center gap-3 text-xl font-extrabold tracking-tight">{settings.logo ? <img src={imageUrl(settings.logo)} alt="" className="size-11 rounded-xl object-contain" /> : <span className="grid size-11 place-items-center rounded-xl bg-[var(--catalog-accent)] text-white"><ShoppingBag className="size-5" /></span>}{settings.name}</a>
      <nav className="flex items-center gap-5 text-sm font-semibold"><a href="#produtos" className="hidden sm:block">Catálogo</a>{contact && <a href={contact} target="_blank" rel="noopener noreferrer" className="flex items-center gap-2"><MessageCircle className="size-4" /><span className="hidden sm:inline">Fale com a gente</span></a>}</nav>
    </div></header>
    <section className={`mx-auto grid max-w-6xl gap-8 px-5 py-12 sm:px-8 sm:py-16 ${settings.cover ? 'md:grid-cols-2 md:items-center' : ''}`}>
      <div><p className="mb-4 text-xs font-extrabold uppercase tracking-[.2em] text-[var(--catalog-accent)]">Uma seleção feita para você</p><h1 className="max-w-2xl text-4xl font-extrabold leading-[1.1] tracking-[-.045em] sm:text-5xl">{settings.headline}</h1><p className="mt-5 max-w-xl whitespace-pre-line text-base leading-7 text-muted-foreground">{settings.description}</p><a href="#produtos" className="mt-7 inline-flex items-center gap-3 border-b border-[var(--catalog-accent)] pb-2 text-sm font-bold text-[var(--catalog-accent)]">Explorar o catálogo <ArrowRight className="size-4" /></a></div>
      {settings.cover && <img src={imageUrl(settings.cover)} alt={`Seleção de produtos de ${settings.name}`} className="aspect-[4/3] w-full rounded-[28px] object-cover" />}
    </section>
    <section id="produtos" className="mx-auto max-w-6xl scroll-mt-6 px-5 pb-16 sm:px-8">
      <div className="flex flex-wrap items-end justify-between gap-5 border-t border-border pt-8"><div><h2 className="text-2xl font-extrabold tracking-tight">Nosso catálogo</h2><p className="mt-1 text-sm text-muted-foreground">{products.length ? `${products.length} produto${products.length === 1 ? '' : 's'} para conhecer` : 'Novidades em breve'}</p></div><div className="relative w-full sm:w-72"><Search className="absolute left-3 top-3 size-4 text-muted-foreground" /><Input aria-label="Buscar produtos" placeholder="O que você procura?" value={search} onChange={e => setSearch(e.target.value)} className="h-10 rounded-full bg-card pl-10" /></div></div>
      <div className="my-6 flex flex-wrap gap-2" aria-label="Categorias">{categories.map(c => <Button key={c} onClick={() => setCategory(c)} variant={category === c ? 'default' : 'outline'} aria-pressed={category === c} className={`rounded-full px-4 ${category === c ? 'bg-[var(--catalog-accent)] text-white' : ''}`}>{c}</Button>)}</div>
      {filtered.length ? <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(p => <article key={p.id} className="overflow-hidden rounded-3xl border border-border bg-card"><a href={`/produto/${p.id}`} className="group block"><div className="aspect-square overflow-hidden bg-muted">{p.images[0] ? <img src={imageUrl(p.images[0])} alt={p.name} loading="lazy" className="h-full w-full object-contain p-4 transition duration-300 group-hover:scale-105" /> : <div className="grid h-full place-items-center text-muted-foreground"><ShoppingBag className="size-12" /></div>}</div><div className="p-5"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-muted-foreground">{p.category || 'Coleção'}</p><h3 className="mt-2 text-lg font-extrabold">{p.name}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-muted-foreground">{p.description}</p><div className="mt-5 flex items-center justify-between gap-2"><span className="font-bold text-[var(--catalog-accent)]">{settings.showPrices && p.price !== null ? money(p.price) : 'Consulte condições'}</span><span className="flex items-center gap-1 text-xs font-semibold">Ver detalhes <ArrowRight className="size-4" /></span></div></div></a></article>)}</div> : <div className="rounded-3xl border border-dashed border-border bg-card/70 px-5 py-16 text-center"><PackageOpen className="mx-auto size-10 text-[var(--catalog-accent)]" /><h3 className="mt-5 text-xl font-bold">{products.length ? 'Nenhum produto encontrado' : 'Estamos preparando nossa seleção'}</h3><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-muted-foreground">{products.length ? 'Tente outro nome ou escolha uma categoria diferente.' : 'Os produtos aparecerão aqui assim que forem publicados. Volte em breve para conferir.'}</p>{products.length > 0 && <Button variant="outline" className="mt-5" onClick={() => { setSearch(''); setCategory('Todos'); }}>Limpar filtros</Button>}</div>}
    </section>
    <footer className="border-t border-border"><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-4 px-5 py-7 text-xs text-muted-foreground sm:px-8"><span>{settings.name} · Catálogo online</span><a href="/admin" className="flex items-center gap-2 hover:text-foreground"><LockKeyhole className="size-3.5" />Área administrativa</a></div></footer>
  </main>;
}
