'use client';
import { useState } from 'react';
import { ArrowUp, Check, ExternalLink, ImagePlus, LockKeyhole, LogOut, Package, Plus, Save, Settings2, ShoppingBag, WandSparkles, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { imageUrl, money, type CatalogData, type Product } from '@/lib/catalog-types';

const blankProduct = (): Product => ({ id: '', name: '', category: '', description: '', price: null, dimensions: '', colors: '', images: [], published: false, position: 0, revision: 0 });
async function request(path: string, data?: unknown): Promise<CatalogData> {
  const r = await fetch(path, data === undefined ? { cache: 'no-store' } : { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) });
  const result = await r.json() as CatalogData & { error?: string }; if (!r.ok) throw new Error(result.error || 'Não foi possível salvar.'); return result;
}
export default function CatalogAdmin({ initial }: { initial: CatalogData }) {
  const [data, setData] = useState(initial); const [tab, setTab] = useState('products');
  const [product, setProduct] = useState<Product | null>(null); const [price, setPrice] = useState('');
  const [settings, setSettings] = useState(initial.settings); const [busy, setBusy] = useState(false); const [dirty, setDirty] = useState(false);
  const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const notify = (e: unknown) => setError(e instanceof Error ? e.message : 'Não foi possível concluir.');
  const canLeave = () => !dirty || window.confirm('Há alterações não salvas. Deseja descartá-las?');
  const select = (p: Product | null) => { if (!canLeave()) return; setProduct(p ? { ...p, images: [...p.images] } : blankProduct()); setPrice(p?.price === null || p?.price === undefined ? '' : (p.price / 100).toFixed(2).replace('.', ',')); setDirty(false); setError(''); setMessage(''); };
  const patch = (v: Partial<Product>) => { setProduct(p => p ? { ...p, ...v } : null); setDirty(true); };
  const refresh = async () => { if (!canLeave()) return; setBusy(true); try { const next = await request('/api/admin/catalog'); setData(next); setSettings(next.settings); setProduct(null); setDirty(false); setError(''); setMessage('Lista atualizada.'); } catch (e) { notify(e); } finally { setBusy(false); } };
  return <main className="min-h-screen"><header className="border-b border-border bg-card"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 px-5 py-5 sm:px-8"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-primary text-primary-foreground"><ShoppingBag className="size-5" /></span><div><p className="font-extrabold">VitrineAI</p><p className="text-xs text-muted-foreground">Seu painel privado</p></div></div><div className="flex items-center gap-4 text-sm font-semibold"><a href="/" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 text-primary">Ver catálogo <ExternalLink className="size-4" /></a><Button variant="outline" disabled={busy} onClick={async () => { if (!canLeave()) return; setBusy(true); try { await request('/api/auth/logout', {}); window.location.assign('/entrar'); } catch(e) { notify(e); setBusy(false); } }}><LogOut />Sair</Button></div></div></header>
    <div className="mx-auto max-w-7xl px-5 py-8 sm:px-8"><div className="mb-7 flex flex-wrap gap-2" aria-label="Áreas do administrador">{[['products','Produtos',<Package key="p" />],['settings','Aparência e contato',<Settings2 key="s" />],['security','Minha senha',<LockKeyhole key="l" />]].map(([key,label,icon]) => <Button key={String(key)} variant={tab === key ? 'default' : 'outline'} disabled={busy} className="h-10 px-4" onClick={() => { if (!canLeave()) return; setTab(String(key)); setDirty(false); setSettings(data.settings); setProduct(null); setError(''); setMessage(''); }}>{icon}{label}</Button>)}<a href="/admin/studio" className="flex h-10 items-center gap-2 rounded-lg border border-border px-4 text-sm font-semibold" onClick={e => { if (!canLeave()) e.preventDefault(); }}><WandSparkles className="size-4" />Studio de anúncios</a></div>
      <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">Configurações do catálogo</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight">{tab === 'products' ? 'Sua vitrine, do seu jeito.' : tab === 'settings' ? 'Dê a sua cara ao catálogo.' : 'Seu acesso, protegido.'}</h1><p className="mt-2 text-sm text-muted-foreground">{tab === 'products' ? 'Cadastre, edite e escolha o que seus clientes podem ver.' : tab === 'settings' ? 'Fotos, identidade e contato salvos para todos os visitantes.' : 'A senha é exclusiva do painel. Clientes não precisam entrar.'}</p></div>{tab !== 'security' && <Button variant="outline" disabled={busy} onClick={refresh}>Atualizar dados</Button>}</div>
      <div aria-live="polite">{message && <p className="mb-5 flex items-center gap-2 rounded-xl bg-primary/10 p-4 text-sm text-primary"><Check className="size-4" />{message}</p>}{error && <p role="alert" className="mb-5 rounded-xl bg-destructive/10 p-4 text-sm text-destructive">{error}</p>}</div>
      {tab === 'products' && <div className="grid items-start gap-6 lg:grid-cols-[minmax(250px,.75fr)_minmax(0,1.5fr)]"><section className="admin-card"><div className="mb-5 flex items-center justify-between"><h2 className="font-extrabold">Produtos ({data.products.length})</h2><Button disabled={busy} onClick={() => select(null)}><Plus />Novo</Button></div><p className="mb-4 text-xs text-muted-foreground">{data.products.filter(p => p.published).length} publicados · {data.products.filter(p => !p.published).length} rascunhos</p><div className="space-y-2">{data.products.map(p => <button key={p.id} disabled={busy} onClick={() => select(p)} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-left ${product?.id === p.id ? 'border-primary bg-primary/5' : 'border-border hover:bg-muted'}`}>
        {p.images[0] ? <img src={imageUrl(p.images[0])} alt="" className="size-14 rounded-lg bg-muted object-contain" /> : <span className="grid size-14 shrink-0 place-items-center rounded-lg bg-muted"><Package className="size-5" /></span>}<span className="min-w-0"><span className="block truncate text-sm font-bold">{p.name}</span><span className="mt-1 block text-xs text-muted-foreground">{p.published ? 'Publicado' : 'Rascunho'} · {p.price === null ? 'Sob consulta' : money(p.price)}</span></span>
      </button>)}{!data.products.length && <div className="rounded-xl border border-dashed border-border px-4 py-9 text-center"><Package className="mx-auto size-7 text-primary" /><p className="mt-3 text-sm font-semibold">Seu primeiro produto começa aqui.</p><p className="mt-2 text-xs leading-5 text-muted-foreground">Clique em Novo, adicione as fotos e publique quando estiver pronto.</p></div>}</div></section>
      {product ? <form className="admin-card" onSubmit={async e => { e.preventDefault(); setError(''); setMessage(''); const normalized = price.trim().replace(',', '.'); if (normalized && !/^\d+(\.\d{1,2})?$/.test(normalized)) { setError('Informe um preço válido, como 129,90, sem separador de milhar.'); return; } setBusy(true); try { const next = await request('/api/admin/product', { ...product, price: normalized ? Math.round(Number(normalized) * 100) : null }); setData(next); setProduct(null); setDirty(false); setMessage(product.published ? 'Produto salvo e disponível no catálogo.' : 'Rascunho salvo. Somente você pode vê-lo.'); } catch(e) { notify(e); } finally { setBusy(false); } }}><fieldset disabled={busy} className="space-y-5"><div className="flex items-center justify-between"><h2 className="text-xl font-extrabold">{product.id ? 'Editar produto' : 'Novo produto'}</h2>{product.id && product.published && <a href={`/produto/${product.id}`} target="_blank" rel="noopener noreferrer" className="text-xs text-primary underline">Ver publicado</a>}</div>
        <Field label="Nome do produto"><Input required maxLength={120} value={product.name} onChange={e => patch({ name: e.target.value })} placeholder="Ex.: Poltrona Luna" /></Field>
        <div className="grid gap-4 sm:grid-cols-2"><Field label="Categoria"><Input maxLength={80} value={product.category} onChange={e => patch({ category: e.target.value })} placeholder="Ex.: Móveis e decoração" /></Field><Field label="Preço em R$ (opcional)"><Input inputMode="decimal" value={price} onChange={e => { setPrice(e.target.value); setDirty(true); }} placeholder="129,90" /></Field></div>
        <PhotoPicker title="Fotos do produto · a primeira é a capa" ids={product.images} max={5} onChange={images => patch({ images })} busy={busy} setBusy={setBusy} onError={notify} />
        <Field label="Descrição"><Textarea rows={5} maxLength={5000} value={product.description} onChange={e => patch({ description: e.target.value })} placeholder="Materiais, benefícios e informações reais do produto." /></Field>
        <div className="grid gap-4 sm:grid-cols-2"><Field label="Medidas"><Input maxLength={300} value={product.dimensions} onChange={e => patch({ dimensions: e.target.value })} placeholder="Ex.: 80 × 70 × 90 cm (L × P × A)" /></Field><Field label="Cores disponíveis"><Input maxLength={300} value={product.colors} onChange={e => patch({ colors: e.target.value })} placeholder="Ex.: Azul, bege e preto" /></Field></div>
        <Field label="Ordem no catálogo (menores aparecem primeiro)"><Input type="number" min={0} max={9999} required value={product.position} onChange={e => patch({ position: Number(e.target.value) })} /></Field>
        <label className="flex items-start gap-3 rounded-xl border border-border bg-muted/50 p-4"><input type="checkbox" checked={product.published} onChange={e => patch({ published: e.target.checked })} className="mt-1 accent-[var(--primary)]" /><span><span className="block text-sm font-bold">Publicar no catálogo</span><span className="mt-1 block text-xs leading-5 text-muted-foreground">Ao salvar, todos poderão ver este produto e suas fotos. Desmarque para manter como rascunho.</span></span></label>
        <Button type="submit" className="h-11 w-full"><Save />{busy ? 'Salvando…' : 'Salvar produto'}</Button>
      </fieldset></form> : <div className="admin-card grid min-h-80 place-items-center text-center"><div><ShoppingBag className="mx-auto size-12 text-primary/40" /><h2 className="mt-4 text-xl font-bold">Tudo pronto para sua seleção</h2><p className="mt-2 max-w-sm text-sm leading-6 text-muted-foreground">Selecione um produto para editar ou crie seu primeiro item. Nenhum produto de exemplo será publicado automaticamente.</p><Button className="mt-5" disabled={busy} onClick={() => select(null)}><Plus />Adicionar produto</Button></div></div>}</div>}
      {tab === 'settings' && <form className="admin-card max-w-3xl" onSubmit={async e => { e.preventDefault(); setError(''); setMessage(''); setBusy(true); try { const next = await request('/api/admin/settings', settings); setData(next); setSettings(next.settings); setDirty(false); setMessage('Configurações salvas. O catálogo já está atualizado.'); } catch(e) { notify(e); } finally { setBusy(false); } }}><fieldset disabled={busy} className="space-y-6">
        <Field label="Nome da loja"><Input required maxLength={80} value={settings.name} onChange={e => { setSettings({ ...settings, name: e.target.value }); setDirty(true); }} /></Field>
        <Field label="Título de boas-vindas"><Input required maxLength={140} value={settings.headline} onChange={e => { setSettings({ ...settings, headline: e.target.value }); setDirty(true); }} /></Field>
        <Field label="Apresentação do catálogo"><Textarea maxLength={1000} value={settings.description} onChange={e => { setSettings({ ...settings, description: e.target.value }); setDirty(true); }} /></Field>
        <div className="grid gap-5 sm:grid-cols-2"><PhotoPicker title="Logo da loja" ids={settings.logo ? [settings.logo] : []} max={1} busy={busy} setBusy={setBusy} onError={notify} onChange={ids => { setSettings(s => ({ ...s, logo: ids[0] || '' })); setDirty(true); }} /><PhotoPicker title="Foto de destaque do catálogo" ids={settings.cover ? [settings.cover] : []} max={1} busy={busy} setBusy={setBusy} onError={notify} onChange={ids => { setSettings(s => ({ ...s, cover: ids[0] || '' })); setDirty(true); }} /></div>
        <Field label="Cor de destaque"><Input type="color" value={settings.accent} onChange={e => { setSettings({ ...settings, accent: e.target.value }); setDirty(true); }} className="h-11 max-w-32" /></Field>
        <Field label="WhatsApp de atendimento (país + DDD + número)"><Input inputMode="tel" maxLength={15} pattern="[0-9]{10,15}|^$" value={settings.whatsapp} onChange={e => { setSettings({ ...settings, whatsapp: e.target.value.replace(/\D/g, '') }); setDirty(true); }} placeholder="5511999999999" /><span className="text-xs font-normal text-muted-foreground">Opcional. Ao preencher e salvar, o número de atendimento ficará público.</span></Field>
        <label className="flex items-center gap-3 text-sm font-semibold"><input type="checkbox" checked={settings.showPrices} onChange={e => { setSettings({ ...settings, showPrices: e.target.checked }); setDirty(true); }} className="accent-[var(--primary)]" />Exibir preços aos clientes</label>
        <Button type="submit" className="h-11 w-full"><Save />{busy ? 'Salvando…' : 'Salvar configurações'}</Button>
      </fieldset></form>}
      {tab === 'security' && <PasswordSettings busy={busy} setBusy={setBusy} onError={notify} onSuccess={() => { setError(''); setMessage('Senha alterada. As outras sessões foram encerradas.'); }} />}
    </div></main>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block space-y-2 text-sm font-semibold">{label}{children}</label>; }
function PhotoPicker({ title, ids, max, onChange, busy, setBusy, onError }: { title: string; ids: string[]; max: number; onChange: (ids: string[]) => void; busy: boolean; setBusy: (busy: boolean) => void; onError: (e: unknown) => void }) {
  return <div className="space-y-3"><h3 className="text-sm font-semibold">{title}</h3><div className="flex flex-wrap gap-3">{ids.map((id, i) => <div key={id} className="relative w-28 rounded-xl border border-border bg-muted p-1"><img src={imageUrl(id)} alt={`Foto ${i + 1}`} className="aspect-square w-full rounded-lg object-contain" /><div className="mt-1 flex justify-between gap-1"><Button type="button" size="icon-xs" variant="outline" disabled={busy || i === 0} aria-label={`Usar foto ${i + 1} como capa`} onClick={() => onChange([id, ...ids.filter(x => x !== id)])}><ArrowUp /></Button><Button type="button" size="icon-xs" variant="outline" disabled={busy} aria-label={`Remover foto ${i + 1}`} onClick={() => onChange(ids.filter(x => x !== id))}><X /></Button></div></div>)}</div>
    <label className={`flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed border-primary/40 bg-primary/5 p-4 text-xs font-bold text-primary ${busy ? 'opacity-50' : ''}`}><ImagePlus />{busy ? 'Aguarde…' : ids.length >= max ? 'Trocar foto(s)' : 'Enviar foto(s)'}<input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" multiple={max > 1} disabled={busy} onChange={async e => { const files = Array.from(e.target.files || []); e.target.value = ''; if (!files.length) return; const next = ids.length >= max ? [] : [...ids]; if (files.length + next.length > max) { onError(new Error(`Use no máximo ${max} foto(s).`)); return; } setBusy(true); try { for (const file of files) { if (!['image/png','image/jpeg','image/webp'].includes(file.type) || file.size > 8 * 1024 * 1024) throw new Error('Envie JPG, PNG ou WEBP com até 8 MB.'); const r = await fetch('/api/admin/upload', { method: 'POST', headers: { 'Content-Type': file.type }, body: file }); const d = await r.json() as { error?: string; id: string }; if (!r.ok) throw new Error(d.error); next.push(d.id); } onChange(next); } catch(err) { onError(err); } finally { setBusy(false); } }} /></label><p className="text-[11px] font-normal text-muted-foreground">JPG, PNG ou WEBP · até 8 MB por foto · máximo {max}. As alterações aparecem após salvar.</p>
  </div>;
}
function PasswordSettings({ busy, setBusy, onError, onSuccess }: { busy: boolean; setBusy: (v: boolean) => void; onError: (e: unknown) => void; onSuccess: () => void }) {
  const [current, setCurrent] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState('');
  return <form className="admin-card max-w-xl" onSubmit={async e => { e.preventDefault(); if (password !== confirm) { onError(new Error('As novas senhas precisam ser iguais.')); return; } setBusy(true); try { await request('/api/admin/password', { currentPassword: current, password }); setCurrent(''); setPassword(''); setConfirm(''); onSuccess(); } catch(e) { onError(e); } finally { setBusy(false); } }}><fieldset disabled={busy} className="space-y-5"><h2 className="text-xl font-extrabold">Alterar minha senha</h2><p className="text-sm leading-6 text-muted-foreground">Use pelo menos 12 caracteres. Ao alterar, os outros dispositivos precisarão entrar novamente.</p><Field label="Senha atual"><Input type="password" autoComplete="current-password" required minLength={12} maxLength={128} value={current} onChange={e => setCurrent(e.target.value)} /></Field><Field label="Nova senha"><Input type="password" autoComplete="new-password" required minLength={12} maxLength={128} value={password} onChange={e => setPassword(e.target.value)} /></Field><Field label="Repita a nova senha"><Input type="password" autoComplete="new-password" required minLength={12} maxLength={128} value={confirm} onChange={e => setConfirm(e.target.value)} /></Field><Button type="submit" className="h-11 w-full"><LockKeyhole />Salvar nova senha</Button></fieldset></form>;
}
