'use client';
import { useState } from 'react';
import { ArrowLeft, MessageCircle, Package, Ruler, Palette } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { imageUrl, money, type CatalogSettings, type Product } from '@/lib/catalog-types';
export default function ProductDetail({ product: p, settings }: { product: Product; settings: CatalogSettings }) {
  const [active, setActive] = useState(0);
  const contact = settings.whatsapp ? `https://wa.me/${settings.whatsapp}?text=${encodeURIComponent(`Olá! Tenho interesse em ${p.name}. Pode me passar mais informações?`)}` : '';
  return <main className="mx-auto max-w-6xl px-5 py-8 sm:px-8"><header className="mb-10 flex items-center justify-between gap-4 border-b border-border pb-6"><a href="/" className="font-extrabold">{settings.name}</a><a href="/#produtos" className="flex items-center gap-2 text-sm font-semibold text-primary"><ArrowLeft className="size-4" />Voltar ao catálogo</a></header><div className="grid gap-8 lg:grid-cols-2 lg:gap-14"><section aria-label="Fotos do produto"><div className="grid aspect-square place-items-center overflow-hidden rounded-3xl border border-border bg-card">{p.images[active] ? <img src={imageUrl(p.images[active])} alt={`${p.name} — foto ${active + 1}`} className="h-full w-full object-contain p-5" /> : <Package className="size-16 text-muted-foreground" />}</div><div className="mt-4 flex flex-wrap gap-3">{p.images.map((id, i) => <Button key={id} aria-label={`Ver foto ${i + 1}`} aria-pressed={active === i} variant="outline" className={`h-20 w-20 overflow-hidden p-1 ${active === i ? 'border-primary ring-1 ring-primary' : ''}`} onClick={() => setActive(i)}><img src={imageUrl(id)} alt="" className="h-full w-full object-contain" /></Button>)}</div></section><section><p className="text-xs font-extrabold uppercase tracking-[.15em] text-primary">{p.category || 'Nosso catálogo'}</p><h1 className="mt-4 text-4xl font-extrabold tracking-[-.04em]">{p.name}</h1><p className="mt-5 text-2xl font-bold">{settings.showPrices && p.price !== null ? money(p.price) : 'Consulte condições'}</p><p className="mt-6 whitespace-pre-line text-sm leading-7 text-muted-foreground">{p.description}</p><dl className="mt-7 space-y-3">{p.dimensions && <div className="rounded-2xl border border-border bg-card p-4"><dt className="flex items-center gap-2 text-xs font-bold"><Ruler className="size-4 text-primary" />Medidas</dt><dd className="mt-2 text-sm text-muted-foreground">{p.dimensions}</dd></div>}{p.colors && <div className="rounded-2xl border border-border bg-card p-4"><dt className="flex items-center gap-2 text-xs font-bold"><Palette className="size-4 text-primary" />Cores disponíveis</dt><dd className="mt-2 text-sm text-muted-foreground">{p.colors}</dd></div>}</dl>{contact ? <a href={contact} target="_blank" rel="noopener noreferrer" style={{ backgroundColor: settings.accent }} className="mt-8 flex items-center justify-center gap-3 rounded-xl p-4 text-sm font-bold text-white"><MessageCircle className="size-5" />Tenho interesse · falar no WhatsApp</a> : <p className="mt-8 rounded-xl bg-muted p-4 text-sm text-muted-foreground">Entre em contato com a loja para consultar disponibilidade e condições.</p>}<p className="mt-4 text-xs leading-5 text-muted-foreground">Consulte a disponibilidade antes de comprar. Este catálogo não realiza pagamentos.</p></section></div></main>;
}
